she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('<int:pk>/edit-story/', views.EditStoryView.as_view(), name='editStory'),
    path('<int:pk>/comment/', views.AddCommentView.as_view(), name='addComment'),
    path('<int:pk>/delete-story/', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('delete-success/', views.delete_success_view, name='deleteSuccess'),
    path('user/<int:pk>/', views.AuthorStories.as_view(), name='authorStories'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include ('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView
from .views import ViewAccountView
from .views import AllAccountsView
from . import views

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('<int:pk>/', ViewAccountView.as_view(), name='viewAccount'),
    path('users/<int:pk>/', AllAccountsView.as_view(), name='viewAllAccounts'),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    # author = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    modified_date = models.DateTimeField(auto_now=True)
    content = models.TextField()
    news_image = models.URLField(blank=True)

class Comment(models.Model):
    story = models.ForeignKey(NewsStory, related_name="comments", on_delete=models.CASCADE)
    author = models.ForeignKey(get_user_model(), related_name="comments", on_delete=models.CASCADE)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# this lets us get all the user stuff Django provides (username, password etc), but then we can also add to it
class CustomUser(AbstractUser):
    profile_image = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    pass

    # this gives me the name of the user on screen
    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory, Comment

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content', 'news_image']
        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'), 
            attrs={'class':'form-control',
            'placeholder':'Select a date',
            'type':'date'}),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'bio', 'profile_image']


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'bio', 'profile_image']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory, Comment
from .forms import StoryForm, CommentForm
from users.models import CustomUser
from django.shortcuts import render, get_object_or_404


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.all()
        return context


class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm
        context["comments"] = Comment.objects.order_by('-created_date')
        return context


class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['add_story_view'] = True
        return context

    def form_valid(self, form):
        # this means to set the author as the user currently logged in
        form.instance.author = self.request.user
        return super().form_valid(form)


class EditStoryView(generic.edit.UpdateView):
    form_class = StoryForm
    model = NewsStory
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['add_story_view'] = False
        return context

    def get_queryset(self):
        return NewsStory.objects.all()


class AddCommentView(generic.CreateView):
    form_class = CommentForm
    template_name = 'news/createComment.html'
    context_object_name = 'comments'

    def form_valid(self, form):
        form.instance.author = self.request.user
        pk = self.kwargs.get("pk")
        story = get_object_or_404(NewsStory, pk=pk)
        form.instance.story = story
        return super().form_valid(form)

    def get_queryset(self):
        return Comment.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.order_by('-created_date')
        return context

    def get_success_url(self) -> str:
        pk = self.kwargs.get("pk")
        return reverse_lazy("news:story", kwargs={'pk':pk})


# ----- simple success page to confirm deletion of story ----- 
def delete_success_view(request):
    return render(request, 'news/deleteSuccess.html')


class DeleteStoryView(generic.edit.DeleteView):
    model = NewsStory
    template_name = 'news/deleteView.html'
    success_url = reverse_lazy('news:deleteSuccess')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['story'] = NewsStory.objects.get(id=self.kwargs['pk'])
        return context


# new class for viewing authors stories
class AuthorStories(generic.ListView):
    template_name = 'news/authorStories.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.filter(author_id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.filter(author_id=self.kwargs['pk'])
        context['author'] = CustomUser.objects.get(id=self.kwargs['pk'])
        return context

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm


class CreateAccountView(CreateView):
	form_class = CustomUserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'users/createAccount.html'

class ViewAccountView(generic.DetailView):
	model = CustomUser
	template_name = 'users/viewAccount.html'
	success_url = reverse_lazy('login')

class AllAccountsView(generic.DetailView):
	model = CustomUser
	template_name = 'users/viewAllAccounts.html'
	success_url = reverse_lazy('login')

she_codes_news/news/templates/news/authorStories.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    <div class="auth-details">
        <h2>{{ author }}</h2>
        <div class="auth-details-wrapper">
            <img class="prof_image_stories" src="{{ author.profile_image }}" alt="{{ author.username }} profile picture">
            <div>
                <p class="auth-bio" >{{ author.bio }}</p>
            </div>
        </div>
    </div>

   <h3>Stories by {{ author }}</h3>
<div id="all-stories">
    {% if latest_stories %}
        {% for story in all_stories %}
            {% include "./storyCard.html" with story=story %}
        {% endfor %}
    {% else %}
        <p>No stories are available.</p>
    {% endif %}
</div>
{% endblock %}

she_codes_news/news/templates/news/commentCard.html
<section class="comment-card">
    <p id="comment-author"> - {{ comment.author }}</p>
    <p>{{ comment.created_date|date:'D, d M y h.i a' }}</p>
    <p>{{ comment.content }}</p>
</section>

she_codes_news/news/templates/news/createComment.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<div class="create-story">
    <h2>Add comment</h2>
<form id="comment-form" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if request.user.is_authenticated %}
    <input class="submit-button" type="submit" value="Submit">
    {% else %}
    <p class="warning-label">You are not logged in. Please log in to comment on stories.</p>
    <a class="log-button" href="{% url 'login' %}">Login</a>
    {% endif %}
</form>
</div>
{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<div class="create-story">
    {% if add_story_view %}
    <h2 class="form-h2">Create new story</h2>
    {% else %}
    <h2 class="form-h2">Edit story</h2>
    {% endif %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if request.user.is_authenticated %}
    <input class="submit-button" type="submit" value="Submit">
    {% else %}
    <p class="warning-label">You are not logged in. Please log in to submit your story.</p>
    <a class="log-button" href="{% url 'login' %}">Log in</a>
    {% endif %}
</form>
</div>
{% endblock %}

she_codes_news/news/templates/news/deleteSuccess.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<section>
    <h2>Delete successful</h2>
     <p>You have deleted the story.</p>
    <a class="log-button" href="{% url 'news:index' %}">Return to all news stories</a>
</section>
{% endblock %}

she_codes_news/news/templates/news/deleteView.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<section>
    <h2>Delete news story</h2>
    <form method="post">
        {% csrf_token %}
     <p>Are you sure you want to delete "{{ story.title }}"?</p>
        {{ form }}
     <input class="submit-button" type="submit" value="Confirm">
    <a class="log-button" href="{% url 'news:story' story.id %}">Cancel</a>
    </form>
</section>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

   <!-- <h2>View by author</h2> -->
   <!-- for user in users, include username -->
   <!-- <a href="">View stories by {{ user.username }}</a> -->

   <h2 class="main-h2" >Latest News</h2>
<!-- this may need images and links -->
    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <h2 class="main-h2" >All News</h2>
    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<section id="story">
<div id="story-wrapper">
    <img src="{{ story.news_image }}"/>
    <h2>{{ story.title }}</h2>
    <p class="auth-pub">Published: {{ story.pub_date|date:'d M y' }}</p>
    <p class="auth-pub">View stories by author: <a class="view-stories" href="{% url 'news:authorStories' story.author.id %}">{{ story.author }}</a> </p>
    <div id="story-content">
        {{ story.content|linebreaks }}
    </div>
</div>
<div id="comment-wrapper">
    <h3>Comments</h3>
    {% if story.comments.count %}
        {% for comment in story.comments.all %}
            {% include "./commentCard.html" with comment=comment %}
        {% endfor %}
    {% else %}
    <p>No comments yet.</p>
    {% endif %}
    {% if request.user.is_authenticated %}
    <form id="comment-form" method="POST" action="{% url 'news:addComment' story.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="submit-button" type="submit" value="Add comment">
    </form>
    {% endif %}
</div>

</div>
{% if request.user.is_authenticated %}
<div id="user_storyadmin">
    <h3>User admin</h3>
    <p>Last edited: {{ story.modified_date|date:'D d M y, h.i a'}}</p>
    <div>
    <a class="log-button" href="{% url 'news:editStory' story.id %}">Edit story</a>
    <a class="log-button" href="{% url 'news:deleteStory' story.id %}">Delete story</a>
    </div>
</div>
{% endif %}
</section>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if position < 5 %}
            <img src="{{ story.news_image }}">
            <!-- <img src="../static/news/images/placeholder-{{ position }}.jpg"> -->
        {% else %}
            <img src="{{ story.news_image }}">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>By {{ story.author }}</h4>
            <h4>{{ story.pub_date|date:'d M y' }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Hayley van Waas">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    </head>
    {% block stylesheets %}{% endblock %}
    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She <span id="h1">{Codes}</span> News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>
        <main>
        {% block content %}{% endblock %}
        <!-- content blocks here -->
        </main>
        <footer></footer>
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
    
    <a href="{% url 'users:viewAccount' request.user.id %}">{{ user.username }}</a>
    <a href="{% url 'news:newStory' %}">Write New Story</a>
    {% if user.is_superuser %}
    <a href="{% url 'admin:index' %}">Admin</a>
    {% endif %}
    <!-- <a href="{% url 'users:viewAllAccounts' request.user.id %}">View accounts</a> -->
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<section id="login-form">
<h2 class="form-h2">Create Account</h2>
<form method="post">
    <!-- csrf token is a security feature to prevent people stealing your credentials -->
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Submit</button>
</form>
</section>
{% endblock %}

she_codes_news/users/templates/users/viewAccount.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'users/styles.css' %}">
{% endblock %}

{% block content %}
<div class="auth-details">
    <h2>Hello {{ user.username }}</h2>
    <div class="auth-details-wrapper">
        <img class="prof_image" src="{{ user.profile_image }}" alt="{{ user.username }} profile picture">
        <div>
            <p><span class="bio-heading">Name:</span> {{ user.username }}</p>
            <p><span class="bio-heading">Email:</span> <a href="mailto:{{user.email}}">{{ user.email }}</a></p>
            <p class="bio-heading">Bio:</p>
            <p>{{ user.bio }}</p>
        </div>
    </div>
</div>
<!-- insert a form here to edit details -->

<!-- <p>Change username</p>
<p>Change email</p>
<p>Edit bio</p>
<p>Upload profile picture</p> -->
{% endblock %}

she_codes_news/users/templates/users/viewAllAccounts.html
{% extends 'base.html' %}

{% block content %}
<h2>View Accounts</h2>

<p>Hello {{ user.username }}</p>

<!-- re-write this to check for user accounts -->
<div>
    {% if latest_stories %}
        {% for story in latest_stories %}
            {% include "./storyCard.html" with story=story position=forloop.counter %}
        {% endfor %}
    {% else %}
        <p>No accounts registered.</p>
    {% endif %}
</div>

{% endblock %}